language: php

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    - php: 7.0
    - php: 7.1
    - php: hhvm
      sudo: required
      dist: trusty
      group: edge
    - php: hhvm-3.9
      sudo: required
      dist: trusty
      group: edge

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/php-cs-fixer fix src/ --rules=@PSR2
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
